# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# if Rails.env == "development"
#   10.times do |i|
#     User.create!(name: "Test#{i + 1}", email: "test#{i + 1}@gmail.com", password: "123456", password_confirmation: "123456")
#   end
# end


# Category.create(name: "トップス")
# Category.create(name: "アウター")
# Category.create(name: "ワンピース")
# Category.create(name: "スカート")
# Category.create(name: "パンツ")
# Category.create(name: "セットアップ")
# Category.create(name: "フォーマル")
# Category.create(name: "スニーカー")
# Category.create(name: "シューズ")
# Category.create(name: "ブーツ")
# Category.create(name: "帽子")
# Category.create(name: "アクセサリー")
# Category.create(name: "バッグ")


# # A
Brand.create(name: "A BATHING APE")
Brand.create(name: "A.P.C")
Brand.create(name: "Acne Studios")
Brand.create(name: "ADAM ET ROPE")
Brand.create(name: "ADDICTION")
Brand.create(name: "adidas")
Brand.create(name: "Aesop")
Brand.create(name: "Aeta")
Brand.create(name: "agnes b.")
Brand.create(name: "AGNONA")
Brand.create(name: "AHKAH")
Brand.create(name: "AKANE USTUNOMIYA")
Brand.create(name: "AKIKOAOKI")
Brand.create(name: "AKIRANAKA")
Brand.create(name: "ALAIA")
Brand.create(name: "alian mikli")
Brand.create(name: "ALANUI")
Brand.create(name: "ALBETRA FERRETTI")
Brand.create(name: "ALBION")
Brand.create(name: "ALDEN")
Brand.create(name: "ALETTE BLANC")
Brand.create(name: "Alexander McQueen")
Brand.create(name: "alexander wang")
Brand.create(name: "ALEXIS MABILLE")
Brand.create(name: "alice + olivia")
Brand.create(name: "alice auaa")
Brand.create(name: "ALLEGE")
Brand.create(name: "AMACA")
Brand.create(name: "AMBELL")
Brand.create(name: "AMBUSH")
Brand.create(name: "ami alexandre mattiussi")
Brand.create(name: "amiu.c")
Brand.create(name: "Amplitude")
Brand.create(name: "ANDERSEN-ANDERSEN")
Brand.create(name: "aniary")
Brand.create(name: "ANN DEMEULEMEESTER")
Brand.create(name: "ANNA SUI")
Brand.create(name: "ANREALAGE")
Brand.create(name: "ANTEPRIMA")
Brand.create(name: "ANTIPAST")
Brand.create(name: "ANTIQULOTHES")
Brand.create(name: "ANYA HINDMARCH")
Brand.create(name: "Aquascutum")
Brand.create(name: "aramis")
Brand.create(name: "ARCTERYX")
Brand.create(name: "ARMANI")
Brand.create(name: "Arobe")
Brand.create(name: "ASEEDONCLOUD")
Brand.create(name: "ASICS")
Brand.create(name: "atmos")
Brand.create(name: "ato")
Brand.create(name: "ATSUSHI NAKASHIMA")
Brand.create(name: "ATTACHMENT")
Brand.create(name: "AUBERCY")
Brand.create(name: "AUDEMARS PIGUET")
Brand.create(name: "AULA")
Brand.create(name: "AURALEE")
Brand.create(name: "AUTHENTIC SHOE & Co.")
Brand.create(name: "AVIE")
Brand.create(name: "ayame")
Brand.create(name: "ayame i wear design")
Brand.create(name: "ayumi.mitsukane")
Brand.create(name: "AYURA")
Brand.create(name: "AZUL by moussy")

# # B
Brand.create(name: "B.A")
Brand.create(name: "Baccarat")
Brand.create(name: "BALENCIAGA")
Brand.create(name: "Bally")
Brand.create(name: "BALMAIN")
Brand.create(name: "BALMUNG")
Brand.create(name: "Barbour")
Brand.create(name: "BATONER")
Brand.create(name: "BAUM UND PFERDGARTEN")
Brand.create(name: "BEAMS")
Brand.create(name: "beautiful people")
Brand.create(name: "BED j.w FORD")
Brand.create(name: "bedsidedrama")
Brand.create(name: "BEDWIN & THE HEARTBREAKERS")
Brand.create(name: "Belstaff")
Brand.create(name: "BEN TAVERNITI UNRAVEL PROJECT")
Brand.create(name: "bench")
Brand.create(name: "BERING")
Brand.create(name: "Berluti")
Brand.create(name: "Bershka")
Brand.create(name: "BIRKENSTOCK")
Brand.create(name: "BlackWeirdos")
Brand.create(name: "blugiri")
Brand.create(name: "Blumarine")
Brand.create(name: "blurhms")
Brand.create(name: "BOBBI BROWN")
Brand.create(name: "bodysong.")
Brand.create(name: "Bonpoint")
Brand.create(name: "Borsalino")
Brand.create(name: "BOTANIST")
Brand.create(name: "BOTTEGA VENETA")
Brand.create(name: "BOUNTY HUNTER")
Brand.create(name: "BRACTMENT")
Brand.create(name: "Breguet")
Brand.create(name: "BREITLING")
Brand.create(name: "Brooks Brothers")
Brand.create(name: "BRUNELLO CUCINELLI")
Brand.create(name: "bubo BARCELONA")
Brand.create(name: "bukht")
Brand.create(name: "BURBERRY")
Brand.create(name: "BUTTERO")
Brand.create(name: "BVLGARI")
Brand.create(name: "BYREDO")