# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# if Rails.env == "development"
#   10.times do |i|
#     User.create!(name: "Test#{i + 1}", email: "test#{i + 1}@gmail.com", password: "123456", password_confirmation: "123456")
#   end
# end


# Category.create(name: "トップス")
# Category.create(name: "アウター")
# Category.create(name: "ワンピース")
# Category.create(name: "スカート")
# Category.create(name: "パンツ")
# Category.create(name: "セットアップ")
# Category.create(name: "フォーマル")
# Category.create(name: "スニーカー")
# Category.create(name: "シューズ")
# Category.create(name: "ブーツ")
# Category.create(name: "帽子")
# Category.create(name: "アクセサリー")
# Category.create(name: "バッグ")


# # A
# Brand.create(name: "A BATHING APE")
# Brand.create(name: "A.P.C")
# Brand.create(name: "Acne Studios")
# Brand.create(name: "ADAM ET ROPE")
# Brand.create(name: "ADDICTION")
# Brand.create(name: "adidas")
# Brand.create(name: "Aesop")
# Brand.create(name: "Aeta")
# Brand.create(name: "agnes b.")
# Brand.create(name: "AGNONA")
# Brand.create(name: "AHKAH")
# Brand.create(name: "AKANE USTUNOMIYA")
# Brand.create(name: "AKIKOAOKI")
# Brand.create(name: "AKIRANAKA")
# Brand.create(name: "ALAIA")
# Brand.create(name: "alian mikli")
# Brand.create(name: "ALANUI")
# Brand.create(name: "ALBETRA FERRETTI")
# Brand.create(name: "ALBION")
# Brand.create(name: "ALDEN")
# Brand.create(name: "ALETTE BLANC")
# Brand.create(name: "Alexander McQueen")
# Brand.create(name: "alexander wang")
# Brand.create(name: "ALEXIS MABILLE")
# Brand.create(name: "alice + olivia")
# Brand.create(name: "alice auaa")
# Brand.create(name: "ALLEGE")
# Brand.create(name: "AMACA")
# Brand.create(name: "AMBELL")
# Brand.create(name: "AMBUSH")
# Brand.create(name: "ami alexandre mattiussi")
# Brand.create(name: "amiu.c")
# Brand.create(name: "Amplitude")
# Brand.create(name: "ANDERSEN-ANDERSEN")
# Brand.create(name: "aniary")
# Brand.create(name: "ANN DEMEULEMEESTER")
# Brand.create(name: "ANNA SUI")
# Brand.create(name: "ANREALAGE")
# Brand.create(name: "ANTEPRIMA")
# Brand.create(name: "ANTIPAST")
# Brand.create(name: "ANTIQULOTHES")
# Brand.create(name: "ANYA HINDMARCH")
# Brand.create(name: "Aquascutum")
# Brand.create(name: "aramis")
# Brand.create(name: "ARCTERYX")
# Brand.create(name: "ARMANI")
# Brand.create(name: "Arobe")
# Brand.create(name: "ASEEDONCLOUD")
# Brand.create(name: "ASICS")
# Brand.create(name: "atmos")
# Brand.create(name: "ato")
# Brand.create(name: "ATSUSHI NAKASHIMA")
# Brand.create(name: "ATTACHMENT")
# Brand.create(name: "AUBERCY")
# Brand.create(name: "AUDEMARS PIGUET")
# Brand.create(name: "AULA")
# Brand.create(name: "AURALEE")
# Brand.create(name: "AUTHENTIC SHOE & Co.")
# Brand.create(name: "AVIE")
# Brand.create(name: "ayame")
# Brand.create(name: "ayame i wear design")
# Brand.create(name: "ayumi.mitsukane")
# Brand.create(name: "AYURA")
# Brand.create(name: "AZUL by moussy")

# B
# Brand.create(name: "B.A")
# Brand.create(name: "Baccarat")
# Brand.create(name: "BALENCIAGA")
# Brand.create(name: "Bally")
# Brand.create(name: "BALMAIN")
# Brand.create(name: "BALMUNG")
# Brand.create(name: "Barbour")
# Brand.create(name: "BATONER")
# Brand.create(name: "BAUM UND PFERDGARTEN")
# Brand.create(name: "BEAMS")
# Brand.create(name: "beautiful people")
# Brand.create(name: "BED j.w FORD")
# Brand.create(name: "bedsidedrama")
# Brand.create(name: "BEDWIN & THE HEARTBREAKERS")
# Brand.create(name: "Belstaff")
# Brand.create(name: "BEN TAVERNITI UNRAVEL PROJECT")
# Brand.create(name: "bench")
# Brand.create(name: "BERING")
# Brand.create(name: "Berluti")
# Brand.create(name: "Bershka")
# Brand.create(name: "BIRKENSTOCK")
# Brand.create(name: "BlackWeirdos")
# Brand.create(name: "blugiri")
# Brand.create(name: "Blumarine")
# Brand.create(name: "blurhms")
# Brand.create(name: "BOBBI BROWN")
# Brand.create(name: "bodysong.")
# Brand.create(name: "Bonpoint")
# Brand.create(name: "Borsalino")
# Brand.create(name: "BOTANIST")
# Brand.create(name: "BOTTEGA VENETA")
# Brand.create(name: "BOUNTY HUNTER")
# Brand.create(name: "BRACTMENT")
# Brand.create(name: "Breguet")
# Brand.create(name: "BREITLING")
# Brand.create(name: "Brooks Brothers")
# Brand.create(name: "BRUNELLO CUCINELLI")
# Brand.create(name: "bubo BARCELONA")
# Brand.create(name: "bukht")
# Brand.create(name: "BURBERRY")
# Brand.create(name: "BUTTERO")
# Brand.create(name: "BVLGARI")
# Brand.create(name: "BYREDO")


# # C
# Brand.create(name: "Calvin Klein")
# Brand.create(name: "CAMPER")
# Brand.create(name: "CANADA GOOSE")
# Brand.create(name: "CANALI")
# Brand.create(name: "Candy Stripper")
# Brand.create(name: "CANMAKE")
# Brand.create(name: "CAROL CHRISTIAN POELL")
# Brand.create(name: "Cartier")
# Brand.create(name: "CARVEN")
# Brand.create(name: "Cath Kidston")
# Brand.create(name: "CEDRIC CHARLIER")
# Brand.create(name: "CELINE")
# Brand.create(name: "Celvoke")
# Brand.create(name: "Champion")
# Brand.create(name: "CHAN LUU")
# Brand.create(name: "CHANEL")
# Brand.create(name: "CHAUMET")
# Brand.create(name: "Children of the discordance")
# Brand.create(name: "Chloe")
# Brand.create(name: "Chopard")
# Brand.create(name: "Christian Louboutin")
# Brand.create(name: "CHRISTOPHE LEMAIRE")
# Brand.create(name: "Christopher Kane")
# Brand.create(name: "CHROME HEARTS")
# Brand.create(name: "Chun Shui Tang")
# Brand.create(name: "Church's")
# Brand.create(name: "CINOH")
# Brand.create(name: "CINQUANTA")
# Brand.create(name: "CITIZEN")
# Brand.create(name: "CIVILIZED")
# Brand.create(name: "CLANE")
# Brand.create(name: "CLARINS")
# Brand.create(name: "CLAUDIA LI")
# Brand.create(name: "cle de peau Beaute")
# Brand.create(name: "CLINIQUE")
# Brand.create(name: "CMMN SWDN")
# Brand.create(name: "COACH")
# Brand.create(name: "Coci la elle")
# Brand.create(name: "coeur femme")
# Brand.create(name: "COFFRET D'OR")
# Brand.create(name: "Columbia")
# Brand.create(name: "COMESANDGOES")
# Brand.create(name: "COMME des GARCONS")
# Brand.create(name: "COMOLI")
# Brand.create(name: "CONVERSE")
# Brand.create(name: "Coohem")
# Brand.create(name: "COS")
# Brand.create(name: "CoSTUME NATIONAL")
# Brand.create(name: "COVERMARK")
# Brand.create(name: "Credor")
# Brand.create(name: "CROCKETT&JONES")
# Brand.create(name: "Cruciani")
# Brand.create(name: "CULLNI")
# Brand.create(name: "CUNE")
# Brand.create(name: "CYCLAS")



# # D
# Brand.create(name: "D'URBAN")
# Brand.create(name: "DAKS")
# Brand.create(name: "Daniel&Bob")
# Brand.create(name: "DE LA MER")
# Brand.create(name: "DECORTE")
# Brand.create(name: "DEMEL")
# Brand.create(name: "DENHAM")
# Brand.create(name: "DEREK LAM")
# Brand.create(name: "DESCENTE")
# Brand.create(name: "DIANA")
# Brand.create(name: "DIANE von FURSTENBERG")
# Brand.create(name: "Dickies")
# Brand.create(name: "DIESEL")
# Brand.create(name: "DIESEL BLACK GOLD")
# Brand.create(name: "DIET BUTCHER SLIM SKIN")
# Brand.create(name: "DIGAWEL")
# Brand.create(name: "DIOR")
# Brand.create(name: "DIOR HOMME")
# Brand.create(name: "diptyque")
# Brand.create(name: "discord Yohji Yamamoto")
# Brand.create(name: "DISCOVERD")
# Brand.create(name: "DITA")
# Brand.create(name: "divka")
# Brand.create(name: "DOLCE&GABBANA")
# Brand.create(name: "DOMENICO+SAVIO")
# Brand.create(name: "Donnah Mabel")
# Brand.create(name: "doublet")
# Brand.create(name: "Dr.martens")
# Brand.create(name: "DRESSUNDRESSED")
# Brand.create(name: "DRIES VAN NOTEN")
# Brand.create(name: "DSQUARED2")
# Brand.create(name: "dunhill")
# Brand.create(name: "DUVETICA")


# E
# Brand.create(name: "e.m")
# Brand.create(name: "EACH OTHER")
# Brand.create(name: "EBONY")
# Brand.create(name: "ED ROBERT JUDSON")
# Brand.create(name: "EDWARD GREEN")
# Brand.create(name: "EDWIN")
# Brand.create(name: "EFFECTEN")
# Brand.create(name: "EFILEVOL")
# Brand.create(name: "Eggs 'in Things")
# Brand.create(name: "elephant TRIBAL fabrics")
# Brand.create(name: "Elizabeth and James")
# Brand.create(name: "EMILIO PUCCI")
# Brand.create(name: "Emily Temple cute")
# Brand.create(name: "EMMETI")
# Brand.create(name: "emmi")
# Brand.create(name: "EMPORIO ARMANI")
# Brand.create(name: "ENFOLD")
# Brand.create(name: "ENGINEERED GARMENTS")
# Brand.create(name: "Enharmonic TAVERN")
# Brand.create(name: "EPOCA")
# Brand.create(name: "EQUIPMENT")
# Brand.create(name: "ERMANNO SCERVINO")
# Brand.create(name: "Ermeneglido Zegna")
# Brand.create(name: "ESPRIQUE")
# Brand.create(name: "est")
# Brand.create(name: "Estee Lauder")
# Brand.create(name: "ESTNATION")
# Brand.create(name: "ETHOSENS")
# Brand.create(name: "ETRO")
# Brand.create(name: "Ezumi")


# F
# Brand.create(name: "F-LAGSTUF-F")
# Brand.create(name: "FABIANA FILIPPI")
# Brand.create(name: "FACETASM")
# Brand.create(name: "FACTOTUM")
# Brand.create(name: "FAGASSENT")
# Brand.create(name: "Faliero Sarti")
# Brand.create(name: "FENDI")
# Brand.create(name: "FILA")
# Brand.create(name: "FILL THE BALL")
# Brand.create(name: "FilMelange")
# Brand.create(name: "FIVEISM x THREE")
# Brand.create(name: "FLICKA")
# Brand.create(name: "FLUMOR")
# Brand.create(name: "foot the coacher")
# Brand.create(name: "FOOTSTOCK ORIGINALS")
# Brand.create(name: "forte forte")
# Brand.create(name: "fragment design")
# Brand.create(name: "Francfranc")
# Brand.create(name: "Frank & Eileen")
# Brand.create(name: "FRANK LEDER")
# Brand.create(name: "FRAPBOIS")
# Brand.create(name: "FRAY I.D")
# Brand.create(name: "FRED PERRY")
# Brand.create(name: "Fulton")
# Brand.create(name: "FUMIE TANAKA")
# Brand.create(name: "FUMIKA_UCHIDA")
# Brand.create(name: "FUMITO GANRYU")
# Brand.create(name: "FURFUR")
# Brand.create(name: "FURLA")


# # G
# Brand.create(name: "G-SHOCK")
# Brand.create(name: "G-star RAW")
# Brand.create(name: "G.V.G.V")
# Brand.create(name: "GalaabenD")
# Brand.create(name: "GAP")
# Brand.create(name: "gelato pique")
# Brand.create(name: "giab's ARCHIVIO")
# Brand.create(name: "GIANFRANCO FERRE")
# Brand.create(name: "Giorgio Armani")
# Brand.create(name: "GIORGIO BRATO")
# Brand.create(name: "GIUSEPPE ZANOTI")
# Brand.create(name: "Givenchy")
# Brand.create(name: "glamb")
# Brand.create(name: "GODIVA")
# Brand.create(name: "GOLDEN GOOSE DELUXE BRAND")
# Brand.create(name: "gomme")
# Brand.create(name: "Gosha Rubchinsky")
# Brand.create(name: "Goutal")
# Brand.create(name: "GRACE CONTINENTAL")
# Brand.create(name: "Graphpaper")
# Brand.create(name: "GREGORY")
# Brand.create(name: "GU")
# Brand.create(name: "GUACAMOLE")
# Brand.create(name: "GUCCI")
# Brand.create(name: "GUERLAIN")
# Brand.create(name: "GUESS")
# Brand.create(name: "GUIDI")


# # H
# Brand.create(name: "H&M")
# Brand.create(name: "h.NAOTO")
# Brand.create(name: "ha | za | ma")
# Brand.create(name: "Haagen-Dazs")
# Brand.create(name: "Haat")
# Brand.create(name: "HACCI")
# Brand.create(name: "HAIDER ACKERMANN")
# Brand.create(name: "Happy Socks")
# Brand.create(name: "HARE")
# Brand.create(name: "Harikae")
# Brand.create(name: "HARRY WINSTON")
# Brand.create(name: "HATRA")
# Brand.create(name: "HAVERSACK")
# Brand.create(name: "HELEN KAMINSKI")
# Brand.create(name: "HELENA RUBINSTEIN")
# Brand.create(name: "Hender Scheme")
# Brand.create(name: "Henri Charpentier")
# Brand.create(name: "HENRI LE ROUX")
# Brand.create(name: "HENRIK VIBSKOV")
# Brand.create(name: "HERMES")
# Brand.create(name: "HERNO")
# Brand.create(name: "HERON PRESTON")
# Brand.create(name: "HIROFU")
# Brand.create(name: "HIROKO BIS")
# Brand.create(name: "HIROKO KOSHINO")
# Brand.create(name: "HISUI HIROKO ITO")
# Brand.create(name: "HOLIDAY")
# Brand.create(name: "House of Holland")
# Brand.create(name: "HTC")
# Brand.create(name: "HUBLOT")
# Brand.create(name: "HUF")
# Brand.create(name: "HUGO BOSS")
# Brand.create(name: "HUTING WORLD")
# Brand.create(name: "HYKE")
# Brand.create(name: "HYSTERIC GLAMOUR")


# I
# Brand.create(name: "Ice-Watch")
# Brand.create(name: "ID DAILYWEAR")
# Brand.create(name: "ikea")
# Brand.create(name: "IKUMI")
# Brand.create(name: "IL BISONTE")
# Brand.create(name: "IN-PROCESS Tokyo")
# Brand.create(name: "INCOTEX")
# Brand.create(name: "INDIVIDUALIZED SHIRTS")
# Brand.create(name: "INVERALLAN")
# Brand.create(name: "IPSA")
# Brand.create(name: "Iroquois")
# Brand.create(name: "ISABEL MARANT")
# Brand.create(name: "ISAMU KATAYAMA BACKLASH")
# Brand.create(name: "ISSEI MIYAKE")
# Brand.create(name: "IWC")


# # J
# Brand.create(name: "J.Crew")
# Brand.create(name: "J.M WESTON")
# Brand.create(name: "JACOB COHEN")
# Brand.create(name: "JAM HOME MADE")
# Brand.create(name: "JAMES PERSE")
# Brand.create(name: "Jane Marple")
# Brand.create(name: "JANE SMITH")
# Brand.create(name: "JASON WU")
# Brand.create(name: "JEAN PAUL GAULTIER")
# Brand.create(name: "JEAN-PAUL HEVIN")
# Brand.create(name: "Jeffery Campbell")
# Brand.create(name: "Jenny Fax")
# Brand.create(name: "Jens")
# Brand.create(name: "JieDa")
# Brand.create(name: "JIL SANDER")
# Brand.create(name: "JILLSTUART")
# Brand.create(name: "JIMMY CHOO")
# Brand.create(name: "JINS")
# Brand.create(name: "JO MALONE LONDON")
# Brand.create(name: "Jocomomola")
# Brand.create(name: "Johan Ku")
# Brand.create(name: "John Galliano")
# Brand.create(name: "JOHN LAWRENCE SULLIVAN")
# Brand.create(name: "JOHN MASON SMITH")
# Brand.create(name: "JOHN SMEDLEY")
# Brand.create(name: "JOHNBULL")
# Brand.create(name: "JOHNSTONS")
# Brand.create(name: "JOSEPH HOMME")
# Brand.create(name: "JOTARO SAITO")
# Brand.create(name: "JOURNAL STANDARD")
# Brand.create(name: "Julien David")
# Brand.create(name: "JULIUS")
# Brand.create(name: "junhashimoto")
# Brand.create(name: "JUNYA WATANABE COMME des GARCONS")
# Brand.create(name: "Just Cavalli")
# Brand.create(name: "JUUN.J")
# Brand.create(name: "JUVENILE HALL ROLLCALL")
# Brand.create(name: "JW anderson")
# Brand.create(name: "J&M DAVIDSON")



# # K
# Brand.create(name: "k3&co.")
# Brand.create(name: "KAMILi")
# Brand.create(name: "KAMISHIMA CHINAMI")
# Brand.create(name: "KANEBO")
# Brand.create(name: "Kappa")
# Brand.create(name: "KAREN WALKER")
# Brand.create(name: "karrimor")
# Brand.create(name: "KATE")
# Brand.create(name: "kate spade new york")
# Brand.create(name: "Kazuki Nagayama")
# Brand.create(name: "KAZUYUKI KUMAGAI")
# Brand.create(name: "KEISUKEYOSHIDA")
# Brand.create(name: "KEITA MARUYAMA")
# Brand.create(name: "KENZO")
# Brand.create(name: "KICS DOCUMENT.")
# Brand.create(name: "KIDILL")
# Brand.create(name: "KIEHL'S SINCE 1851")
# Brand.create(name: "KIIT")
# Brand.create(name: "KIJIMA TAKAYUKI")
# Brand.create(name: "KINO")
# Brand.create(name: "Kirov")
# Brand.create(name: "KITH")
# Brand.create(name: "Kiwanda")
# Brand.create(name: "KOCHE")
# Brand.create(name: "kolor")
# Brand.create(name: "KOTONA")
# Brand.create(name: "KRIZIA")
# Brand.create(name: "kujaku")
# Brand.create(name: "KURO")
# Brand.create(name: "k三")
























































